services:
  - type: web
    name: crop-recommendation-service
    env: python
    buildCommand: pip install -r CropRecommendationSystem/requirements.txt
    startCommand: cd CropRecommendationSystem && gunicorn api:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    plan: free
    autoDeploy: false

  - type: web
    name: plant-disease-service
    env: python
    buildCommand: pip install -r PlantDisease/requirements.txt
    startCommand: cd PlantDisease && gunicorn app:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    plan: free
    autoDeploy: false
